import * as fs from "node:fs";
import * as path from "node:path";
import fg from "fast-glob";
import { Finding, ProjectProfile } from "../../core/types.js";

const GENERATED_DIRS = ["generated", "dist", "build", "openapi-generated", ".next", "out", "target"];

function isGeneratedFile(content: string): boolean {
  const header = content.slice(0, 4_000).toLowerCase();
  return /(?:do not edit[\s,]*(?:this is an )?(?:auto[- ]generated|generated)|code generated|auto[- ]generated|autogenerated|generated file|machine[- ]generated)/i.test(header);
}

export async function analyzeRepository(
  repoRoot: string,
  profile: ProjectProfile
): Promise<{
  findings: Finding[];
  metrics: {
    totalFiles: number;
    largeFiles: { file: string; lines: number }[];
    packageRoots: string[];
    hasGeneratedDirs: string[];
    workflows: Record<string, boolean>;
  };
}> {
  const findings: Finding[] = [];

  // 1. Structure Evaluation using ProjectProfile
  const hasRecognizedPackages = profile.packageRoots.length > 0;
  const hasRecognizedTests = profile.testRoots.length > 0;

  if (!hasRecognizedPackages && profile.entryPoints.length === 0) {
    // Only flag if completely unorganized and cannot recognize any package layout
    findings.push({
      id: "repo-unorganized-structure",
      ruleId: "repo/project-structure",
      category: "repository",
      severity: "low",
      confidence: 0.50,
      needsReview: true,
      title: "Unidentified source code layout",
      description: "Could not identify standard package roots or entry points for this project. Agents may require explicit path guidance in AGENTS.md to navigate the repository.",
      evidence: [
        {
          file: ".",
          snippet: `Ecosystem: ${profile.primaryEcosystem}`,
          source: "filesystem",
        },
      ],
      recommendation: "Document key package directories and entry points in AGENTS.md.",
    });
  }

  // 2. Oversized Files Check (distinguishing test files vs source files)
  const sourceFiles = await fg(["**/*.{ts,tsx,js,jsx,py,go,rs,java,c,cpp}"], {
    cwd: repoRoot,
    ignore: [
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/.git/**",
      "**/.venv/**",
      "**/venv/**",
      "**/target/**",
      "**/out/**",
      "**/coverage/**",
      "**/vendor/**",
      "**/.next/**",
      "**/*.min.js",
      "**/package-lock.json",
      "**/pnpm-lock.yaml",
      "**/yarn.lock",
      "**/generated/**",
    ],
  });

  const largeFiles: { file: string; lines: number }[] = [];

  for (const relFile of sourceFiles) {
    const absPath = path.join(repoRoot, relFile);
    try {
      const content = fs.readFileSync(absPath, "utf-8");
      const lineCount = content.split(/\r?\n/).length;

      // Generated sources are already protected by their generator and do not
      // represent a navigational problem for coding agents. Flagging them as
      // oversized code creates noisy findings in API/schema repositories.
      if (isGeneratedFile(content)) continue;

      const isTestFile =
        relFile.includes("tests/") ||
        relFile.includes("test/") ||
        path.basename(relFile).startsWith("test_") ||
        relFile.includes(".test.") ||
        relFile.includes(".spec.");

      const threshold = isTestFile ? 3000 : 1500;

      if (lineCount > threshold) {
        largeFiles.push({ file: relFile, lines: lineCount });

        findings.push({
          id: `repo-large-file-${relFile.replace(/[^a-zA-Z0-9]/g, "-")}`,
          ruleId: "repo/oversized-source-files",
          category: "repository",
          severity: isTestFile ? "low" : "medium",
          confidence: 0.90,
          title: `Oversized ${isTestFile ? "test suite" : "source"} file: ${relFile} (${lineCount.toLocaleString()} lines)`,
          description: `Files exceeding ${threshold.toLocaleString()} lines may increase agent retrieval latency, expand context window token consumption, and increase patch ambiguity. This indicates potential navigation cost rather than code quality.`,
          evidence: [
            {
              file: relFile,
              snippet: `${lineCount.toLocaleString()} lines`,
              source: relFile,
            },
          ],
          impact: {
            tokens: Math.round(lineCount * 3.5),
            latency: isTestFile ? 2 : 5,
          },
          recommendation: isTestFile
            ? `Consider breaking large test suites into specialized test modules.`
            : `Consider splitting ${relFile} into smaller cohesive sub-modules to ease agent retrieval.`,
        });
      }
    } catch {
      // ignore
    }
  }

  // 3. Generated Code Protection & Discoverability
  // Only protect repository-level build outputs. Nested `target`, `dist`, and
  // `out` directories are frequently intentional test fixtures or per-package
  // artifacts (Cargo and monorepos can contain hundreds of them), so warning
  // about every match would turn a useful guardrail into a false-positive
  // generator. Source scanning still excludes generated directories above.
  const existingGeneratedDirs = (await fg(
    GENERATED_DIRS,
    {
      cwd: repoRoot,
      dot: true,
      onlyDirectories: true,
      unique: true,
      ignore: ["**/.git/**", "**/node_modules/**", "**/.venv/**", "**/venv/**"],
    }
  )).sort((a, b) => a.localeCompare(b));

  if (existingGeneratedDirs.length > 0) {
    const instructionFiles = fg.sync(
      ["**/AGENTS.md", "**/CLAUDE.md", "**/.cursorrules", "**/.cursor/rules/**/*.md", "**/.cursor/rules/**/*.mdc", ".cursor/rules/**/*.md", ".cursor/rules/**/*.mdc"],
      {
        cwd: repoRoot,
        dot: true,
        onlyFiles: true,
        ignore: [
          "**/node_modules/**",
          "**/.git/**",
          "**/dist/**",
          "**/build/**",
          "**/target/**",
          "**/out/**",
          "**/generated/**",
          "**/vendor/**",
          "**/.next/**",
        ],
      }
    );
    let mentionsGeneratedWarning = false;
    for (const inst of instructionFiles) {
      const instPath = path.join(repoRoot, inst);
      if (fs.existsSync(instPath)) {
        const text = fs.readFileSync(instPath, "utf-8").toLowerCase();
        if (
          (text.includes("generated") || existingGeneratedDirs.some((d) => text.includes(d))) &&
          (text.includes("do not edit") ||
            text.includes("never edit") ||
            text.includes("never manually edit") ||
            text.includes("auto-generated"))
        ) {
          mentionsGeneratedWarning = true;
          break;
        }
      }
    }

    if (!mentionsGeneratedWarning) {
      findings.push({
        id: "repo-unprotected-generated-code",
        ruleId: "repo/generated-code-protection",
        category: "repository",
        severity: "medium",
        confidence: 0.85,
        title: `Unprotected generated directories: ${existingGeneratedDirs.join(", ")}`,
        description: `Repository contains build artifacts (${existingGeneratedDirs.join(", ")}), but instructions do not explicitly warn AI agents not to edit them directly. Coding agents frequently hallucinate edits into build outputs instead of source files.`,
        evidence: existingGeneratedDirs.map((dir) => ({
          file: dir,
          snippet: `Directory ${dir}/ exists`,
          source: "filesystem",
        })),
        recommendation: "Add an explicit rule in AGENTS.md: 'Never manually edit files in generated/ or build output directories.'",
      });
    }
  }

  // 4. Critical Workflow Discoverability (Ecosystem-aware!)
  const workflows: Record<string, boolean> = {
    install: false,
    build: false,
    test: false,
    lint: false,
    typecheck: false,
  };

  // Detect workflows based on ecosystem
  if (profile.ecosystems.includes("python")) {
    workflows.install = fs.existsSync(path.join(repoRoot, "requirements.txt")) ||
                         fs.existsSync(path.join(repoRoot, "pyproject.toml")) ||
                         fs.existsSync(path.join(repoRoot, "poetry.lock")) ||
                         fs.existsSync(path.join(repoRoot, "uv.lock"));

    workflows.test = profile.testRoots.length > 0 ||
                     fs.existsSync(path.join(repoRoot, "pytest.ini")) ||
                     (profile.configFiles.python?.includes("pyproject.toml") ?? false);

    workflows.lint = fs.existsSync(path.join(repoRoot, ".pre-commit-config.yaml")) ||
                     fs.existsSync(path.join(repoRoot, "ruff.toml"));

    workflows.build = fs.existsSync(path.join(repoRoot, "setup.py")) ||
                      (profile.configFiles.python?.includes("pyproject.toml") ?? false);
  }

  if (profile.ecosystems.includes("node")) {
    const packageRelativePath = profile.configFiles.node?.find((file) => path.basename(file) === "package.json");
    const pkgPath = packageRelativePath ? path.join(repoRoot, packageRelativePath) : "";
    if (pkgPath && fs.existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
        const scripts = pkg.scripts || {};
        if (pkg.dependencies || pkg.devDependencies) workflows.install = true;
        if (scripts.build || scripts.compile) workflows.build = true;
        if (scripts.test) workflows.test = true;
        if (scripts.lint) workflows.lint = true;
        if (scripts.typecheck || scripts["type-check"] || scripts.tsc) workflows.typecheck = true;
      } catch {
        // ignore
      }
    }
  }

  if (profile.ecosystems.includes("rust")) {
    workflows.install = true; // cargo does it automatically
    workflows.build = true;   // cargo build
    workflows.test = true;    // cargo test
    workflows.lint = true;    // cargo clippy
    workflows.typecheck = true; // cargo check
  }

  if (profile.ecosystems.includes("go")) {
    workflows.install = true; // go get
    workflows.build = true;   // go build
    workflows.test = true;    // go test
    workflows.lint = true;    // go vet
    workflows.typecheck = true; // go build / compile
  }

  return {
    findings,
    metrics: {
      totalFiles: sourceFiles.length,
      largeFiles,
      packageRoots: profile.packageRoots,
      hasGeneratedDirs: existingGeneratedDirs,
      workflows,
    },
  };
}
