import * as fs from "node:fs";
import { evaluateCheck } from "../core/regression/check.js";
import { formatAgentDoctorMarkdown } from "../core/regression/report.js";

interface GitHubEvent {
  pull_request?: {
    number?: number;
    base?: { ref?: string };
  };
}

function readEvent(): GitHubEvent {
  const eventPath = process.env.GITHUB_EVENT_PATH;
  if (!eventPath) return {};

  try {
    return JSON.parse(fs.readFileSync(eventPath, "utf-8")) as GitHubEvent;
  } catch {
    return {};
  }
}

function writeOutput(name: string, value: string): void {
  const outputPath = process.env.GITHUB_OUTPUT;
  if (!outputPath) return;

  // Use the documented multiline output form so the Markdown report remains
  // readable to downstream workflow steps. A deterministic delimiter is
  // enough here because report content is generated by AgentDoctor; the
  // suffix loop also keeps this safe if a future report contains the marker.
  let delimiter = `agentdoctor_${name}_EOF`;
  while (value.includes(delimiter)) delimiter += "_";
  fs.appendFileSync(outputPath, `${name}<<${delimiter}\n${value}\n${delimiter}\n`, "utf-8");
}

function writeSummary(markdown: string): void {
  const summaryPath = process.env.GITHUB_STEP_SUMMARY;
  if (!summaryPath) return;
  fs.appendFileSync(summaryPath, `${markdown}\n`, "utf-8");
}

async function updatePullRequestComment(body: string, token: string, repository: string, issueNumber: number): Promise<void> {
  const headers = {
    Accept: "application/vnd.github+json",
    Authorization: `Bearer ${token}`,
    "X-GitHub-Api-Version": "2022-11-28",
    "Content-Type": "application/json",
  };
  const endpoint = `https://api.github.com/repos/${repository}/issues/${issueNumber}/comments`;
  const listResponse = await fetch(endpoint, { headers });
  if (!listResponse.ok) throw new Error(`GitHub comments API returned ${listResponse.status}`);

  const comments = await listResponse.json() as Array<{ id: number; body?: string }>;
  const existing = comments.find((comment) => comment.body?.includes("<!-- agentdoctor-report -->"));
  const response = existing
    ? await fetch(`${endpoint}/${existing.id}`, {
        method: "PATCH",
        headers,
        body: JSON.stringify({ body }),
      })
    : await fetch(endpoint, {
        method: "POST",
        headers,
        body: JSON.stringify({ body }),
      });

  if (!response.ok) throw new Error(`GitHub comments API returned ${response.status}`);
}

async function main(): Promise<void> {
  const event = readEvent();
  const baselineInput = process.env.AGENTDOCTOR_BASELINE?.trim();
  const baseline = baselineInput || event.pull_request?.base?.ref || undefined;
  const evaluation = await evaluateCheck({
    cwd: process.env.GITHUB_WORKSPACE || process.cwd(),
    minScore: process.env.AGENTDOCTOR_MIN_SCORE || undefined,
    maxRegression: process.env.AGENTDOCTOR_MAX_REGRESSION || undefined,
    failOn: process.env.AGENTDOCTOR_FAIL_ON || undefined,
    baseline,
  });

  const markdown = formatAgentDoctorMarkdown(evaluation);
  writeSummary(markdown);
  writeOutput("score", String(evaluation.result.overallScore));
  writeOutput("baseline-score", evaluation.comparison ? String(evaluation.comparison.baselineScore) : "");
  writeOutput("regression", evaluation.comparison ? String(Math.max(0, -evaluation.comparison.scoreDelta)) : "0");
  writeOutput("regression-count", String(evaluation.comparison?.regressions.length || 0));
  writeOutput("passed", String(evaluation.passed));
  writeOutput("report", markdown);

  const issueNumber = event.pull_request?.number;
  const token = process.env.AGENTDOCTOR_GITHUB_TOKEN?.trim();
  const repository = process.env.GITHUB_REPOSITORY;
  if (issueNumber && token && repository) {
    try {
      await updatePullRequestComment(markdown, token, repository, issueNumber);
    } catch (error) {
      console.warn(`AgentDoctor could not update the PR comment: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  process.exitCode = evaluation.exitCode;
}

main().catch((error) => {
  console.error(`AgentDoctor Action failed: ${error instanceof Error ? error.message : String(error)}`);
  process.exitCode = error && typeof error === "object" && "exitCode" in error
    ? Number((error as { exitCode: number }).exitCode)
    : 1;
});
